### PR TITLE
Fix for Windows 10 IoT Core

### LINKED ISSUE #2: NuimoSDK cannot be used for headless apps due to DispatchOnMainAsync
I want to create a smart home application and I'm doing that using Windows 10 IoT Core.

I'm developing a Background app. Such apps are headless (so they do not have a `CoreApplication.MainView`).

When calling `INuimoController.ConnectAsync()`, the NuimoSDK uses `DispatchOnMainAsync()` to perform some tasks. However, headless apps do not have a `MainView` and the `DispatchOnMainAsync()` function causes a `COMException` when `ConnectionState` is set to `Connecting`.

This means that I cannot use the NuimoSDK for my app because after discovering an `INuimoController` I cannot connect to it.

``` C#
private async void DispatchOnMainAsync(DispatchedHandler dispatchedHandler)
{
    await CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, dispatchedHandler);
}
```

System.Runtime.InteropServices.COMException

```
A method was called at an unexpected time.

Could not create a new view because the main window has not yet been created
```

Stacktrace:

```
   at Windows.ApplicationModel.Core.CoreApplication.get_MainView()
   at NuimoSDK.NuimoBluetoothController.<DispatchOnMainAsync>d__43.MoveNext()
```

### PR DESCRIPTION
**Pull request by hansmbakker**
Patch intended to fix #2 

Remove DispatchOnMainThread (since IoT apps are headless and Dispatcher for the UI thread should be used in the client apps)
Increase CancellationToken for SubscribeForCharacteristicNotifications() (otherwise it would think that connection failed)

### CODE REVIEW

**Comment by larsblumberg** [comment]
Dispatching is currently being discussed in https://github.com/getsenic/nuimo-windows/issues/2

**Comment by larsblumberg** [comment]
@wind-rider Did you have issues with the duration of `SubscribeForCharacteristicNotifications`'s cancellation token?

**Comment by hansmbakker** [comment]
Yes I initially couldn't connect well, until I increased that value.

File: NuimoSDK/NuimoBluetoothController.cs [hunk 1]
```diff
@@ -121,20 +121,23 @@ private void BluetoothGattCallback(GattCharacteristic sender, GattValueChangedEv
                 case CharacteristicsGuids.FlyCharacteristicGuidString:      nuimoGestureEvent = changedValue.ToFlyEvent();      break;
                 default:                                                    nuimoGestureEvent = null;                           break;
             }
-            if (nuimoGestureEvent != null) DispatchOnMainAsync(() => GestureEventOccurred?.Invoke(nuimoGestureEvent));
+            if (nuimoGestureEvent != null)
```
Comment (larsblumberg) [inline NuimoSDK/NuimoBluetoothController.cs]: Please make this a one-liner to be coherent with the coding style of this repo:

`if (nuimoGestureEvent != null) GestureEventOccurred?.Invoke(nuimoGestureEvent);`

**Comment by Inrego** [comment]
Can confirm issues with cancellation token of 1s

**Comment by hansmbakker** [comment]
@larsblumberg done.

It would help if there would be a style guideline for the windows repos that could be integrated in IDEs.

StyleCop is one way how to enforce coding style guidelines.

**Comment by larsblumberg** [comment]
Unfortunately we don't have resources right now to formalize a coding style guide. Please use the existing source code style as a reference for how to format code in pull requests. Thanks!

**Comment by hansmbakker** [comment]
@larsblumberg great, thanks for merging :) when will a new NuGet version be released?

**Comment by larsblumberg** [comment]
Would be great to have #8, #9 and #12 merged, too :)
